# Generated by Django 4.2.2 on 2023-07-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientInfoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_healthinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=30)),
                ('symptoms', models.TextField()),
                ('disease', models.CharField(max_length=200)),
                ('treatment', models.TextField()),
                ('diagnosis_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PatientInfoapp.patient_generalinfo')),
            ],
        ),
    ]
